# 相当于脚本用途的一个声明
name: Maven Central Repo Deployment
# 触发脚本的事件  这里为发布release之后触发
on:
  workflow_dispatch:
  release:
    types: [ released, prereleased ]
# 定义一个发行任务
jobs:
  publish:
    # 任务运行的环境
    runs-on: ubuntu-latest
    # 任务的步骤
    steps:
      # 1. 声明 checkout 仓库代码到工作区
      - name: Checkout Git Repo
        uses: actions/checkout@v3
      # 2. 安装Java 环境 这里会用到的参数就是 Git Action secrets中配置的，
      #    取值要在key前面加  secrets.
      - name: Set up Maven Central Repo
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_CENTRAL_TOKEN
          gpg-private-key: ${{ secrets.GPG_SECRET }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      # 3. 发布到Maven中央仓库
      - name: Publish to Maven Central Repo
        # 这里用到了其他人写的action脚本，详细可以去看他的文档。
        run: mvn clean deploy --batch-mode -Pdeploy -DskipTests=true
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USER }}
          MAVEN_CENTRAL_TOKEN: ${{ secrets.OSSRH_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSWORD }}
